package ergo

import (
	"bytes"
	"text/template"

	"github.com/conflicthq/scuttlebot/internal/config"
)

var ircdTemplate = template.Must(template.New("ircd").Parse(`# Generated by scuttlebot — do not edit manually.
network:
    name: {{.NetworkName}}

server:
    name: {{.ServerName}}
    listeners:
        "{{.IRCAddr}}": {}
    casemapping: ascii
    enforce-utf8: true
    relaymsg:
        enabled: false
    ip-cloaking:
        enabled: false
    lookup-hostnames: false

datastore:
    path: {{.DataDir}}/ircd.db
    autoupgrade: true
{{- if .HistoryEnabled}}
    {{- if .PostgresDSN}}
    postgresql:
        enabled: true
        dsn: "{{.PostgresDSN}}"
    {{- else if .MySQLEnabled}}
    mysql:
        enabled: true
        host: "{{.MySQL.Host}}"
        port: {{.MySQL.Port}}
        user: "{{.MySQL.User}}"
        password: "{{.MySQL.Password}}"
        history-database: "{{.MySQL.Database}}"
    {{- end}}
{{- end}}

accounts:
    registration:
        enabled: true
        allow-before-connect: true
        throttling:
            enabled: false
    authentication-enabled: true
    require-sasl:
        enabled: false

channels:
    registration:
        enabled: true

history:
    enabled: {{.HistoryEnabled}}
{{- if .HistoryEnabled}}
    channel-length: 2048
    client-length: 256
    autoresize-window: 3d
    autoreplay-on-join: 0
    chathistory-maxmessages: 1000
    znc-maxmessages: 2048
    restrictions:
        expire-time: 7d
        query-cutoff: none
    persistent:
        enabled: {{.HistoryEnabled}}
        unregistered-channels: false
        registered-channels: opt-in
        direct-messages: opt-in
{{- end}}

api:
    enabled: true
    listener: "{{.APIAddr}}"
    bearer-tokens:
        - "{{.APIToken}}"

logging:
    - method: stderr
      type: "* -userinput -useroutput"
      level: warn

limits:
    nicklen: 32
    channellen: 64
    awaylen: 200
    kicklen: 255
    topiclen: 512

opers:
    scuttlebot:
        class: ircop
        hidden: true
        whois-line: scuttlebot operator

oper-classes:
    ircop:
        title: IRC Operator
        capabilities:
            - oper:local_kill
            - oper:local_ban
            - oper:local_unban
            - oper:remote_kill
            - oper:remote_ban
            - oper:remote_unban
            - oper:rehash
            - oper:die
            - oper:nofakelag
            - oper:relaymsg
            - ban:nick
            - ban:hostname
            - ban:cidr
            - ban:ip
            - samode
            - sajoin
            - snomask
            - vhosts
            - accreg
            - chanreg
            - history
            - defcon
            - massmessage
`))

type ircdTemplateData struct {
	NetworkName    string
	ServerName     string
	IRCAddr        string
	DataDir        string
	APIAddr        string
	APIToken       string
	HistoryEnabled bool
	PostgresDSN    string
	MySQLEnabled   bool
	MySQL          config.MySQLConfig
}

// GenerateConfig renders an ircd.yaml from the given ErgoConfig.
func GenerateConfig(cfg config.ErgoConfig) ([]byte, error) {
	data := ircdTemplateData{
		NetworkName:    cfg.NetworkName,
		ServerName:     cfg.ServerName,
		IRCAddr:        cfg.IRCAddr,
		DataDir:        cfg.DataDir,
		APIAddr:        cfg.APIAddr,
		APIToken:       cfg.APIToken,
		HistoryEnabled: cfg.History.Enabled,
		PostgresDSN:    cfg.History.PostgresDSN,
		MySQLEnabled:   cfg.History.MySQL.Host != "" && cfg.History.PostgresDSN == "",
		MySQL:          cfg.History.MySQL,
	}

	var buf bytes.Buffer
	if err := ircdTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
