// Package auditbot implements the auditbot — immutable agent action audit trail.
//
// auditbot answers: "what did agent X do, and when?"
//
// It records two categories of events:
//  1. IRC-observed: agent envelopes whose type appears in the configured
//     auditTypes set (e.g. task.create, agent.hello), plus presence events
//     (user.join, user.part, user.quit, user.kick, user.nick).
//  2. Registry-injected: credential lifecycle events (registration, rotation,
//     revocation) written directly via Record(), not via IRC.
//
// Entries are append-only. There are no update or delete operations.
package auditbot

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/lrstanley/girc"

	"github.com/conflicthq/scuttlebot/internal/bots/cmdparse"
	"github.com/conflicthq/scuttlebot/pkg/protocol"
)

const botNick = "auditbot"

// EventKind classifies the source of an audit entry.
type EventKind string

const (
	// KindIRC indicates the event was observed on the IRC message stream.
	KindIRC EventKind = "irc"
	// KindRegistry indicates the event was injected by the registry.
	KindRegistry EventKind = "registry"
	// KindSystem indicates the event was generated by the auditbot itself
	// (e.g. throttle summaries).
	KindSystem EventKind = "system"
)

// Event types for user presence changes and audit-system events.
const (
	EventUserJoin       = "user.join"
	EventUserPart       = "user.part"
	EventUserQuit       = "user.quit"
	EventUserKick       = "user.kick"
	EventUserNick       = "user.nick"
	EventAuditThrottled = "system.audit.throttled"
)

// defaultPresenceMax is the default max presence events per window before the
// throttle drops events of that type. Chosen so a normal channel cycle (one
// agent restart, a couple of mode tweaks) never trips the limit, while a
// connection-storm or join-flood gets clipped quickly.
const (
	defaultPresenceMax    = 60
	defaultPresenceWindow = 5 * time.Minute
)

// Entry is an immutable audit record.
type Entry struct {
	At          time.Time
	Kind        EventKind
	Channel     string // empty for registry events
	Nick        string // agent nick (or affected nick for presence events)
	MessageType string // e.g. "task.create", "agent.registered"
	MessageID   string // envelope ID for IRC events; empty for registry events
	Detail      string // human-readable detail (reason, kicker, throttle summary, etc.)
}

// Store persists audit entries. Implementations must be append-only.
type Store interface {
	Append(Entry) error
}

// ThrottleRule configures a fixed-window rate cap for a single event type.
// Max == 0 disables throttling for that event type (uncapped). Window must
// be positive when Max > 0; a zero/negative Window falls back to the default
// presence window.
type ThrottleRule struct {
	Max    int
	Window time.Duration
}

// ThrottleConfig maps audit event type → cap. Event types not present here
// are uncapped.
type ThrottleConfig struct {
	PerType map[string]ThrottleRule
}

// DefaultThrottleConfig returns the conservative default throttle for
// presence churn. KICK is intentionally uncapped because it's rare and
// operationally important; if every kick generates a record, that's fine.
func DefaultThrottleConfig() ThrottleConfig {
	return ThrottleConfig{
		PerType: map[string]ThrottleRule{
			EventUserJoin: {Max: defaultPresenceMax, Window: defaultPresenceWindow},
			EventUserPart: {Max: defaultPresenceMax, Window: defaultPresenceWindow},
			EventUserQuit: {Max: defaultPresenceMax, Window: defaultPresenceWindow},
			EventUserNick: {Max: defaultPresenceMax, Window: defaultPresenceWindow},
			// EventUserKick: uncapped by default — set Max>0 to enable.
		},
	}
}

// throttleBucket tracks one fixed-window counter per event type.
type throttleBucket struct {
	rule        ThrottleRule
	windowStart time.Time
	count       int
	dropped     int
}

// Bot is the auditbot.
type Bot struct {
	ircAddr    string
	password   string
	channels   []string
	auditTypes map[string]struct{}
	store      Store
	log        *slog.Logger
	client     *girc.Client

	mu       sync.Mutex
	throttle ThrottleConfig
	buckets  map[string]*throttleBucket
	now      func() time.Time // overridable for tests
}

// New creates an auditbot. auditTypes is the set of message types to record;
// pass nil or empty to audit all envelope types. The bot is created with
// default presence throttling; override via SetThrottle.
func New(ircAddr, password string, channels []string, auditTypes []string, store Store, log *slog.Logger) *Bot {
	at := make(map[string]struct{}, len(auditTypes))
	for _, t := range auditTypes {
		at[t] = struct{}{}
	}
	return &Bot{
		ircAddr:    ircAddr,
		password:   password,
		channels:   channels,
		auditTypes: at,
		store:      store,
		log:        log,
		throttle:   DefaultThrottleConfig(),
		buckets:    make(map[string]*throttleBucket),
		now:        time.Now,
	}
}

// SetThrottle replaces the bot's throttle configuration. Existing bucket
// state is reset so changes take effect immediately. Safe to call before
// Start; not intended for concurrent use during Start.
func (b *Bot) SetThrottle(cfg ThrottleConfig) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if cfg.PerType == nil {
		cfg.PerType = map[string]ThrottleRule{}
	}
	b.throttle = cfg
	b.buckets = make(map[string]*throttleBucket)
}

// Name returns the bot's IRC nick.
func (b *Bot) Name() string { return botNick }

// Record writes a registry lifecycle event directly to the audit store.
// This is called by the registry on registration, rotation, and revocation —
// not from IRC.
func (b *Bot) Record(nick, eventType, detail string) {
	b.write(Entry{
		Kind:        KindRegistry,
		Nick:        nick,
		MessageType: eventType,
		Detail:      detail,
	})
}

// Start connects to IRC and begins auditing. Blocks until ctx is cancelled.
func (b *Bot) Start(ctx context.Context) error {
	host, port, err := splitHostPort(b.ircAddr)
	if err != nil {
		return fmt.Errorf("auditbot: parse irc addr: %w", err)
	}

	c := girc.New(girc.Config{
		Server:      host,
		Port:        port,
		Nick:        botNick,
		User:        botNick,
		Name:        "scuttlebot auditbot",
		SASL:        &girc.SASLPlain{User: botNick, Pass: b.password},
		PingDelay:   30 * time.Second,
		PingTimeout: 30 * time.Second,
		SSL:         false,
	})

	c.Handlers.AddBg(girc.CONNECTED, func(cl *girc.Client, _ girc.Event) {
		cl.Cmd.Mode(cl.GetNick(), "+B")
		for _, ch := range b.channels {
			cl.Cmd.Join(ch)
		}
		b.log.Info("auditbot connected", "channels", b.channels, "audit_types", b.auditTypesList())
	})

	c.Handlers.AddBg(girc.INVITE, func(cl *girc.Client, e girc.Event) {
		if ch := e.Last(); strings.HasPrefix(ch, "#") {
			cl.Cmd.Join(ch)
		}
	})

	router := cmdparse.NewRouter(botNick)
	router.Register(cmdparse.Command{
		Name:        "query",
		Usage:       "QUERY <nick|#channel>",
		Description: "show recent audit events for a nick or channel",
		Handler:     func(_ *cmdparse.Context, _ string) string { return "not implemented yet" },
	})

	c.Handlers.AddBg(girc.PRIVMSG, func(cl *girc.Client, e girc.Event) {
		if len(e.Params) < 1 {
			return
		}
		// Dispatch commands (DMs and channel messages).
		if reply := router.Dispatch(e.Source.Name, e.Params[0], e.Last()); reply != nil {
			cl.Cmd.Message(reply.Target, reply.Text)
			return
		}
		channel := e.Params[0]
		if !strings.HasPrefix(channel, "#") {
			return // non-command DMs ignored
		}
		text := e.Last()
		env, err := protocol.Unmarshal([]byte(text))
		if err != nil {
			return // non-envelope PRIVMSG ignored
		}
		if !b.shouldAudit(env.Type) {
			return
		}
		nick := ""
		if e.Source != nil {
			nick = e.Source.Name
		}
		b.write(Entry{
			Kind:        KindIRC,
			Channel:     channel,
			Nick:        nick,
			MessageType: env.Type,
			MessageID:   env.ID,
		})
	})

	c.Handlers.AddBg(girc.JOIN, func(_ *girc.Client, e girc.Event) {
		if len(e.Params) == 0 {
			return
		}
		b.handleJoin(e.Params[0], sourceNick(e))
	})

	c.Handlers.AddBg(girc.PART, func(_ *girc.Client, e girc.Event) {
		if len(e.Params) == 0 {
			return
		}
		b.handlePart(e.Params[0], sourceNick(e))
	})

	c.Handlers.AddBg(girc.QUIT, func(cl *girc.Client, e girc.Event) {
		nick := sourceNick(e)
		b.handleQuit(nick, lookupChannels(cl, nick))
	})

	c.Handlers.AddBg(girc.KICK, func(_ *girc.Client, e girc.Event) {
		if len(e.Params) < 2 {
			return
		}
		channel := e.Params[0]
		kicked := e.Params[1]
		reason := ""
		if len(e.Params) >= 3 {
			reason = e.Params[2]
		}
		b.handleKick(channel, kicked, sourceNick(e), reason)
	})

	c.Handlers.AddBg(girc.NICK, func(cl *girc.Client, e girc.Event) {
		oldNick := sourceNick(e)
		newNick := e.Last()
		if newNick == "" || oldNick == "" {
			return
		}
		// Try the old nick first (state may not be mutated yet); fall back to
		// the new nick (state already renamed).
		channels := lookupChannels(cl, oldNick)
		if len(channels) == 0 {
			channels = lookupChannels(cl, newNick)
		}
		b.handleNick(oldNick, newNick, channels)
	})

	b.mu.Lock()
	b.client = c
	b.mu.Unlock()

	errCh := make(chan error, 1)
	go func() {
		if err := c.Connect(); err != nil && ctx.Err() == nil {
			errCh <- err
		}
	}()

	select {
	case <-ctx.Done():
		c.Close()
		return nil
	case err := <-errCh:
		return fmt.Errorf("auditbot: irc connection: %w", err)
	}
}

// Stop disconnects the bot.
func (b *Bot) Stop() {
	if b.client != nil {
		b.client.Close()
	}
}

// handleJoin records a JOIN. Subject to throttling and the audit-type filter.
func (b *Bot) handleJoin(channel, nick string) {
	b.recordPresence(EventUserJoin, channel, nick, "")
}

// handlePart records a PART. Subject to throttling and the audit-type filter.
func (b *Bot) handlePart(channel, nick string) {
	b.recordPresence(EventUserPart, channel, nick, "")
}

// handleQuit records a QUIT — one entry per channel the user was in. If the
// channel set is empty (state already mutated, or untracked), one entry is
// written with empty Channel.
func (b *Bot) handleQuit(nick string, channels []string) {
	if len(channels) == 0 {
		b.recordPresence(EventUserQuit, "", nick, "")
		return
	}
	for _, ch := range channels {
		b.recordPresence(EventUserQuit, ch, nick, "")
	}
}

// handleKick records a KICK. Channel is mandatory (KICK always names it).
// The kicker's nick and reason are stashed in Detail.
func (b *Bot) handleKick(channel, kicked, kicker, reason string) {
	detail := "by=" + kicker
	if reason != "" {
		detail += " reason=" + reason
	}
	b.recordPresence(EventUserKick, channel, kicked, detail)
}

// handleNick records a NICK change — one entry per channel the user shares.
// Detail captures the rename: "old=<from> new=<to>". If the channel set is
// empty, one entry is written with empty Channel.
func (b *Bot) handleNick(oldNick, newNick string, channels []string) {
	detail := "old=" + oldNick + " new=" + newNick
	if len(channels) == 0 {
		b.recordPresence(EventUserNick, "", newNick, detail)
		return
	}
	for _, ch := range channels {
		b.recordPresence(EventUserNick, ch, newNick, detail)
	}
}

// recordPresence applies the audit-type filter and the throttle, then writes
// the entry. Drops are summarized via writeThrottleSummary at window rollover.
func (b *Bot) recordPresence(msgType, channel, nick, detail string) {
	if !b.shouldAudit(msgType) {
		return
	}
	if !b.throttleAdmit(msgType) {
		return
	}
	b.write(Entry{
		Kind:        KindIRC,
		Channel:     channel,
		Nick:        nick,
		MessageType: msgType,
		Detail:      detail,
	})
}

// throttleAdmit returns true when the event should be recorded, false when it
// should be dropped. Drops increment the bucket's dropped counter; window
// rollover emits a single aggregated system.audit.throttled entry summarizing
// the prior window's drops.
func (b *Bot) throttleAdmit(msgType string) bool {
	rule, ok := b.throttle.PerType[msgType]
	if !ok || rule.Max <= 0 {
		return true // uncapped
	}
	window := rule.Window
	if window <= 0 {
		window = defaultPresenceWindow
	}

	now := b.nowFunc()()

	b.mu.Lock()
	bk, exists := b.buckets[msgType]
	if !exists {
		bk = &throttleBucket{rule: ThrottleRule{Max: rule.Max, Window: window}, windowStart: now}
		b.buckets[msgType] = bk
	}
	// Window rollover: flush summary if previous window had drops, then reset.
	if now.Sub(bk.windowStart) >= bk.rule.Window {
		dropped := bk.dropped
		bk.windowStart = now
		bk.count = 0
		bk.dropped = 0
		// Update rule in case config changed between calls.
		bk.rule = ThrottleRule{Max: rule.Max, Window: window}
		b.mu.Unlock()
		if dropped > 0 {
			b.writeThrottleSummary(msgType, dropped, window)
		}
		b.mu.Lock()
	}

	if bk.count < bk.rule.Max {
		bk.count++
		b.mu.Unlock()
		return true
	}
	bk.dropped++
	b.mu.Unlock()
	return false
}

// writeThrottleSummary emits one aggregated audit entry describing the count
// of dropped events of msgType during the just-closed window.
func (b *Bot) writeThrottleSummary(msgType string, dropped int, window time.Duration) {
	b.write(Entry{
		Kind:        KindSystem,
		MessageType: EventAuditThrottled,
		Detail:      fmt.Sprintf("type=%s dropped=%d window=%s", msgType, dropped, window),
	})
}

func (b *Bot) shouldAudit(msgType string) bool {
	if len(b.auditTypes) == 0 {
		return true // audit everything when no filter configured
	}
	_, ok := b.auditTypes[msgType]
	return ok
}

func (b *Bot) write(e Entry) {
	e.At = b.nowFunc()()
	if err := b.store.Append(e); err != nil {
		if b.log != nil {
			b.log.Error("auditbot: failed to write entry",
				"type", e.MessageType,
				"nick", e.Nick,
				"channel", e.Channel,
				"kind", e.Kind,
				"err", err,
			)
		}
	}
}

func (b *Bot) auditTypesList() []string {
	if len(b.auditTypes) == 0 {
		return []string{"*"}
	}
	out := make([]string, 0, len(b.auditTypes))
	for t := range b.auditTypes {
		out = append(out, t)
	}
	return out
}

func (b *Bot) nowFunc() func() time.Time {
	if b.now != nil {
		return b.now
	}
	return time.Now
}

func sourceNick(e girc.Event) string {
	if e.Source == nil {
		return ""
	}
	return e.Source.Name
}

// lookupChannels returns the channels the given nick is known to share with
// this client, via girc's tracked state. Returns an empty slice if the user
// is unknown or tracking is disabled.
func lookupChannels(cl *girc.Client, nick string) []string {
	if cl == nil || nick == "" {
		return nil
	}
	u := cl.LookupUser(nick)
	if u == nil {
		return nil
	}
	out := make([]string, 0, len(u.ChannelList))
	for _, ch := range u.ChannelList {
		if ch != "" {
			out = append(out, ch)
		}
	}
	return out
}

func splitHostPort(addr string) (string, int, error) {
	host, portStr, err := net.SplitHostPort(addr)
	if err != nil {
		return "", 0, fmt.Errorf("invalid address %q: %w", addr, err)
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		return "", 0, fmt.Errorf("invalid port in %q: %w", addr, err)
	}
	return host, port, nil
}
